// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/home/data/entity/home_geofencing_detail_entity.dart';
import 'models/search/data/models/search_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4540303878512426843),
      name: 'SearchModel',
      lastPropertyId: const obx_int.IdUid(2, 3438332537899419124),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8949197422994284706),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3438332537899419124),
            name: 'searchKeyword',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7082283678694823012),
      name: 'HomeGeofencingDetailEntity',
      lastPropertyId: const obx_int.IdUid(5, 8121287403751671307),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8879134801065562158),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4289731446733440699),
            name: 'locationTitle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4522992692482397402),
            name: 'locationSubtitle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3900802631746419205),
            name: 'lat',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8121287403751671307),
            name: 'long',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 7082283678694823012),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    SearchModel: obx_int.EntityDefinition<SearchModel>(
        model: _entities[0],
        toOneRelations: (SearchModel object) => [],
        toManyRelations: (SearchModel object) => {},
        getId: (SearchModel object) => object.id,
        setId: (SearchModel object, int id) {
          object.id = id;
        },
        objectToFB: (SearchModel object, fb.Builder fbb) {
          final searchKeywordOffset = fbb.writeString(object.searchKeyword);
          fbb.startTable(3);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, searchKeywordOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final searchKeywordParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final object = SearchModel(idParam, searchKeywordParam);

          return object;
        }),
    HomeGeofencingDetailEntity:
        obx_int.EntityDefinition<HomeGeofencingDetailEntity>(
            model: _entities[1],
            toOneRelations: (HomeGeofencingDetailEntity object) => [],
            toManyRelations: (HomeGeofencingDetailEntity object) => {},
            getId: (HomeGeofencingDetailEntity object) => object.id,
            setId: (HomeGeofencingDetailEntity object, int id) {
              object.id = id;
            },
            objectToFB: (HomeGeofencingDetailEntity object, fb.Builder fbb) {
              final locationTitleOffset = fbb.writeString(object.locationTitle);
              final locationSubtitleOffset =
                  fbb.writeString(object.locationSubtitle);
              fbb.startTable(6);
              fbb.addInt64(0, object.id ?? 0);
              fbb.addOffset(1, locationTitleOffset);
              fbb.addOffset(2, locationSubtitleOffset);
              fbb.addFloat64(3, object.lat);
              fbb.addFloat64(4, object.long);
              fbb.finish(fbb.endTable());
              return object.id ?? 0;
            },
            objectFromFB: (obx.Store store, ByteData fbData) {
              final buffer = fb.BufferContext(fbData);
              final rootOffset = buffer.derefObject(0);
              final latParam =
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
              final longParam =
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
              final locationTitleParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGet(buffer, rootOffset, 6, '');
              final locationSubtitleParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGet(buffer, rootOffset, 8, '');
              final idParam = const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4);
              final object = HomeGeofencingDetailEntity(latParam, longParam,
                  locationTitleParam, locationSubtitleParam,
                  id: idParam);

              return object;
            })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SearchModel] entity fields to define ObjectBox queries.
class SearchModel_ {
  /// See [SearchModel.id].
  static final id =
      obx.QueryIntegerProperty<SearchModel>(_entities[0].properties[0]);

  /// See [SearchModel.searchKeyword].
  static final searchKeyword =
      obx.QueryStringProperty<SearchModel>(_entities[0].properties[1]);
}

/// [HomeGeofencingDetailEntity] entity fields to define ObjectBox queries.
class HomeGeofencingDetailEntity_ {
  /// See [HomeGeofencingDetailEntity.id].
  static final id = obx.QueryIntegerProperty<HomeGeofencingDetailEntity>(
      _entities[1].properties[0]);

  /// See [HomeGeofencingDetailEntity.locationTitle].
  static final locationTitle =
      obx.QueryStringProperty<HomeGeofencingDetailEntity>(
          _entities[1].properties[1]);

  /// See [HomeGeofencingDetailEntity.locationSubtitle].
  static final locationSubtitle =
      obx.QueryStringProperty<HomeGeofencingDetailEntity>(
          _entities[1].properties[2]);

  /// See [HomeGeofencingDetailEntity.lat].
  static final lat = obx.QueryDoubleProperty<HomeGeofencingDetailEntity>(
      _entities[1].properties[3]);

  /// See [HomeGeofencingDetailEntity.long].
  static final long = obx.QueryDoubleProperty<HomeGeofencingDetailEntity>(
      _entities[1].properties[4]);
}
