// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/home/data/alarm_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3563796519752165657),
    name: 'AlarmModel',
    lastPropertyId: const obx_int.IdUid(7, 2892051553758161175),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1720317728450881902),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 395243949700324875),
        name: 'destinationName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2702561620005632617),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2552730373801559809),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6200567500351436441),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5858403091647437922),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2892051553758161175),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 3563796519752165657),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AlarmModel: obx_int.EntityDefinition<AlarmModel>(
      model: _entities[0],
      toOneRelations: (AlarmModel object) => [],
      toManyRelations: (AlarmModel object) => {},
      getId: (AlarmModel object) => object.id,
      setId: (AlarmModel object, int id) {
        object.id = id;
      },
      objectToFB: (AlarmModel object, fb.Builder fbb) {
        final destinationNameOffset = fbb.writeString(object.destinationName);
        final addressOffset = fbb.writeString(object.address);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, destinationNameOffset);
        fbb.addOffset(2, addressOffset);
        fbb.addFloat64(3, object.latitude);
        fbb.addFloat64(4, object.longitude);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addBool(6, object.isActive);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final destinationNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final latitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final longitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final isActiveParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final object = AlarmModel(
          id: idParam,
          destinationName: destinationNameParam,
          address: addressParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          createdAt: createdAtParam,
          isActive: isActiveParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AlarmModel] entity fields to define ObjectBox queries.
class AlarmModel_ {
  /// See [AlarmModel.id].
  static final id = obx.QueryIntegerProperty<AlarmModel>(
    _entities[0].properties[0],
  );

  /// See [AlarmModel.destinationName].
  static final destinationName = obx.QueryStringProperty<AlarmModel>(
    _entities[0].properties[1],
  );

  /// See [AlarmModel.address].
  static final address = obx.QueryStringProperty<AlarmModel>(
    _entities[0].properties[2],
  );

  /// See [AlarmModel.latitude].
  static final latitude = obx.QueryDoubleProperty<AlarmModel>(
    _entities[0].properties[3],
  );

  /// See [AlarmModel.longitude].
  static final longitude = obx.QueryDoubleProperty<AlarmModel>(
    _entities[0].properties[4],
  );

  /// See [AlarmModel.createdAt].
  static final createdAt = obx.QueryDateProperty<AlarmModel>(
    _entities[0].properties[5],
  );

  /// See [AlarmModel.isActive].
  static final isActive = obx.QueryBooleanProperty<AlarmModel>(
    _entities[0].properties[6],
  );
}
